main: com.github.mundotv789123.McMBot
load: STARTUP
name: McMBot
version: 2.0
website: https://github.com/mundotv789123
author: mundotv789123
commands:
  mcmbot:
    permission: 'mcmbot.admin'
    usage: '/mcmbot reload'
