config:
  token: token do bot
  login_chat: id do canal de login
  permission: 'mcmbot.staff'
  refused_command: 'ban-ip %ip% &cVocê foi banido pelo &emcmbot.'

kick_messages:
  discord_not_found: '&aSeu discord não foi vinculado a sua conta.'
  
discord_messages:
  permission: '%player% (%ip%) entrou no servidor porém não teve o discord vinculado.'
  login: '%discord% Sua conta [%player%] acabou de logar no servidor, confirmar acesso?'
  success: '%discord% Acesso liberado!'
  
accounts:
#- 'nickMinecraft:idDiscord'